server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fitnessuser
    username: root
    password: Utkarsh@123
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/